#!/bin/bash -e

echo run kk-irc-bot and proxy in screen

#git clone --depth 1 git://github.com/phus/goagent.git
sudo -ukk -i bash -c "cd /home/kk/dev/goagent/local ; screen -d -m python ./proxy.py "
sudo -ukk -i bash -c "cd /home/kk/dev/kk-irc-bot ; screen -d -m ./irc.rb ub.conf & "
#sudo -ukk -i bash -c "cd /home/kk/dev/kk-irc-bot;screen -d -m ./irc.rb avplayer.conf &"


